-- MySQL Script generated by MySQL Workbench
-- 06/15/17 10:39:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema spsec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spsec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spsec` DEFAULT CHARACTER SET utf8 ;
USE `spsec` ;

-- -----------------------------------------------------
-- Table `spsec`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`address` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ZIPCODE` INT(11) NULL DEFAULT NULL,
  `COUNTRY` VARCHAR(15) NOT NULL,
  `DISTRICT` VARCHAR(40) NULL DEFAULT NULL,
  `INTERIOR` VARCHAR(255) NULL DEFAULT NULL,
  `NUM` INT(11) NULL DEFAULT NULL,
  `STATE` VARCHAR(15) NOT NULL,
  `STREET` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`article` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `LINK` VARCHAR(300) NOT NULL,
  `TITLE` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_4lvs8ighs0advk6a12igf28uk` (`LINK` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`tags` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_rykdcj4mhocnvglvy3bnhikib` (`NAME` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`article_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`article_tags` (
  `ARTICLE_ID` BIGINT(20) NOT NULL,
  `TAG_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ARTICLE_ID`, `TAG_ID`),
  INDEX `FKlcsmj6o0a7lqjmsru6addiole` (`TAG_ID` ASC),
  CONSTRAINT `FKew1occm6ueo3jcc2725t2iw3j`
    FOREIGN KEY (`ARTICLE_ID`)
    REFERENCES `spsec`.`article` (`id`),
  CONSTRAINT `FKlcsmj6o0a7lqjmsru6addiole`
    FOREIGN KEY (`TAG_ID`)
    REFERENCES `spsec`.`tags` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`authority` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`benefit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`benefit` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `DISCOUNT` DECIMAL(9,2) NULL DEFAULT NULL,
  `POINTS` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`type` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_jfqfpp4dm9ugky0ygm2r46jk4` (`NAME` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`brand` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(30) NOT NULL,
  `SHORTNAME` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_4soxyeki7itboi9ao2geeenrj` (`NAME` ASC),
  UNIQUE INDEX `UK_fgeyn2b7u7wnrfmba2gk3lfc8` (`SHORTNAME` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`product` (
  `PRODUCT_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` TEXT NULL DEFAULT NULL,
  `ENABLED` TINYINT(1) NOT NULL DEFAULT '1',
  `NAME` VARCHAR(40) NOT NULL,
  `PRICE` DECIMAL(9,2) NOT NULL,
  `BRAND_ID` BIGINT(20) NULL DEFAULT NULL,
  `TYPE_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`PRODUCT_ID`),
  INDEX `FKsj2lk079hwjngnn3o9o183b6q` (`BRAND_ID` ASC),
  INDEX `FK279tro333i6anih53vy4t18hr` (`TYPE_ID` ASC),
  CONSTRAINT `FK279tro333i6anih53vy4t18hr`
    FOREIGN KEY (`TYPE_ID`)
    REFERENCES `spsec`.`type` (`id`),
  CONSTRAINT `FKsj2lk079hwjngnn3o9o183b6q`
    FOREIGN KEY (`BRAND_ID`)
    REFERENCES `spsec`.`brand` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`benefit_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`benefit_product` (
  `BENEFIT_ID` BIGINT(20) NOT NULL,
  `PRODUCT_ID` BIGINT(20) NOT NULL,
  INDEX `FKq9ke42uuiunfg00ttjmgsvhg2` (`PRODUCT_ID` ASC),
  INDEX `FK2o8a54eha8uaakaefggv6ryfy` (`BENEFIT_ID` ASC),
  CONSTRAINT `FK2o8a54eha8uaakaefggv6ryfy`
    FOREIGN KEY (`BENEFIT_ID`)
    REFERENCES `spsec`.`benefit` (`id`),
  CONSTRAINT `FKq9ke42uuiunfg00ttjmgsvhg2`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `spsec`.`product` (`PRODUCT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_riore06il3igyibh7h1ksq64p` (`NAME` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`flavor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`flavor` (
  `FLAVOR_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`FLAVOR_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`product_flavor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`product_flavor` (
  `EXISTENCE` BIGINT(20) NOT NULL,
  `FLAV_ID` BIGINT(20) NOT NULL,
  `PROD_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`FLAV_ID`, `PROD_ID`),
  INDEX `FKa5os1gmgvtnnixfutnato963v` (`PROD_ID` ASC),
  CONSTRAINT `FKa5os1gmgvtnnixfutnato963v`
    FOREIGN KEY (`PROD_ID`)
    REFERENCES `spsec`.`product` (`PRODUCT_ID`),
  CONSTRAINT `FKha20339e23vk1cnl18f3b414c`
    FOREIGN KEY (`FLAV_ID`)
    REFERENCES `spsec`.`flavor` (`FLAVOR_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(50) NOT NULL,
  `ENABLED` BIT(1) NOT NULL,
  `FIRSTNAME` VARCHAR(50) NOT NULL,
  `LASTPASSWORDRESETSTATE` DATETIME NOT NULL,
  `LASTNAME` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(100) NOT NULL,
  `PHONE` BIGINT(20) NULL DEFAULT NULL,
  `POINTS` BIGINT(20) NULL DEFAULT NULL,
  `USERNAME` VARCHAR(20) NOT NULL,
  `ADDRESS` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `USERNAME` (`USERNAME` ASC),
  INDEX `FK27E3CBBBA66A84` (`ADDRESS` ASC),
  CONSTRAINT `FK27E3CBBBA66A84`
    FOREIGN KEY (`ADDRESS`)
    REFERENCES `spsec`.`address` (`id`),
  CONSTRAINT `FKc2pqo2xet7hd8t5n60y3youwv`
    FOREIGN KEY (`ADDRESS`)
    REFERENCES `spsec`.`address` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`purchase_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`purchase_order` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CONCLUDED` BIT(1) NULL DEFAULT NULL,
  `PURCHASE_TIME` DATETIME NULL DEFAULT NULL,
  `TOTAL` DECIMAL(14,2) NOT NULL,
  `TRACK_NUMBER` VARCHAR(50) NOT NULL,
  `ADDRESS` BIGINT(20) NULL DEFAULT NULL,
  `GIFT` BIGINT(20) NULL DEFAULT NULL,
  `OWNER` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKqrcu8p3a50w5kfbsqvmvn9wm` (`ADDRESS` ASC),
  INDEX `FK9dvqqpkhmp3jp9u32npmuif3f` (`GIFT` ASC),
  INDEX `FK27w01alef4j5oi2hgyx9tv4da` (`OWNER` ASC),
  CONSTRAINT `FK27w01alef4j5oi2hgyx9tv4da`
    FOREIGN KEY (`OWNER`)
    REFERENCES `spsec`.`user` (`id`),
  CONSTRAINT `FK9dvqqpkhmp3jp9u32npmuif3f`
    FOREIGN KEY (`GIFT`)
    REFERENCES `spsec`.`benefit` (`id`),
  CONSTRAINT `FKqrcu8p3a50w5kfbsqvmvn9wm`
    FOREIGN KEY (`ADDRESS`)
    REFERENCES `spsec`.`address` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`order_detail` (
  `QUANTITY` INT(11) NULL DEFAULT NULL,
  `FLAV_ID` BIGINT(20) NOT NULL,
  `PROD_ID` BIGINT(20) NOT NULL,
  `ORDER_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ORDER_ID`, `FLAV_ID`, `PROD_ID`),
  INDEX `FKmqe2lw1fkswatvkf4uc7u70s5` (`FLAV_ID` ASC, `PROD_ID` ASC),
  CONSTRAINT `FKmqe2lw1fkswatvkf4uc7u70s5`
    FOREIGN KEY (`FLAV_ID` , `PROD_ID`)
    REFERENCES `spsec`.`product_flavor` (`FLAV_ID` , `PROD_ID`),
  CONSTRAINT `FKn4hsciae9beyk0kc0tdgajqxp`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `spsec`.`purchase_order` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`product_category` (
  `PRODUCT_ID` BIGINT(20) NOT NULL,
  `CATEGORY_ID` BIGINT(20) NOT NULL,
  INDEX `FK3xw1sbaa29r534jvedimdd7md` (`CATEGORY_ID` ASC),
  INDEX `FKa7245ly271mb0crlhxwhhppsq` (`PRODUCT_ID` ASC),
  CONSTRAINT `FK3xw1sbaa29r534jvedimdd7md`
    FOREIGN KEY (`CATEGORY_ID`)
    REFERENCES `spsec`.`category` (`id`),
  CONSTRAINT `FKa7245ly271mb0crlhxwhhppsq`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `spsec`.`product` (`PRODUCT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`promotion_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`promotion_rule` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `PROMOTION_TYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MIN_AMOUNT` INT(11) NULL DEFAULT NULL,
  `MINPURCHASE` DECIMAL(14,2) NOT NULL,
  `PERCENTAGE` INT(11) NULL DEFAULT NULL,
  `POINTS` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`promo_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`promo_categories` (
  `PROMO_RULE_ID` BIGINT(20) NOT NULL,
  `CATEGORY_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`PROMO_RULE_ID`, `CATEGORY_ID`),
  INDEX `FKldr0j2kkjsnmfywjh2syaiqm` (`CATEGORY_ID` ASC),
  CONSTRAINT `FKavd4m4qn47own5tmkn203c2cd`
    FOREIGN KEY (`PROMO_RULE_ID`)
    REFERENCES `spsec`.`promotion_rule` (`id`),
  CONSTRAINT `FKldr0j2kkjsnmfywjh2syaiqm`
    FOREIGN KEY (`CATEGORY_ID`)
    REFERENCES `spsec`.`category` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`promo_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`promo_product` (
  `PROMO_RULE_ID` BIGINT(20) NOT NULL,
  `PRODUCT_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`PROMO_RULE_ID`, `PRODUCT_ID`),
  INDEX `FKr1t872u00hx2ev4eghtcjytp5` (`PRODUCT_ID` ASC),
  CONSTRAINT `FKg11ufomhebq4fyac7hmslrbsf`
    FOREIGN KEY (`PROMO_RULE_ID`)
    REFERENCES `spsec`.`promotion_rule` (`id`),
  CONSTRAINT `FKr1t872u00hx2ev4eghtcjytp5`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `spsec`.`product` (`PRODUCT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`promo_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`promo_types` (
  `PROMO_RULE_ID` BIGINT(20) NOT NULL,
  `PRODUCT_TYPE_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`PROMO_RULE_ID`, `PRODUCT_TYPE_ID`),
  INDEX `FKamwcj5vl8g6ssih78x1n01y3w` (`PRODUCT_TYPE_ID` ASC),
  CONSTRAINT `FKamwcj5vl8g6ssih78x1n01y3w`
    FOREIGN KEY (`PRODUCT_TYPE_ID`)
    REFERENCES `spsec`.`type` (`id`),
  CONSTRAINT `FKryst39vqhsqrmqq5gly0q3kg6`
    FOREIGN KEY (`PROMO_RULE_ID`)
    REFERENCES `spsec`.`promotion_rule` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`promotion` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` TEXT NOT NULL,
  `DISPLAY_NAME` VARCHAR(30) NULL DEFAULT NULL,
  `ENABLED` BIT(1) NULL DEFAULT NULL,
  `END_DATE` DATETIME NULL DEFAULT NULL,
  `INCLUSIVE` TINYINT(1) NULL DEFAULT '1',
  `START_DATE` DATETIME NULL DEFAULT NULL,
  `promotionrule_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKp9bcmcraoyuk0u342jsv4p0sy` (`promotionrule_id` ASC),
  CONSTRAINT `FKp9bcmcraoyuk0u342jsv4p0sy`
    FOREIGN KEY (`promotionrule_id`)
    REFERENCES `spsec`.`promotion_rule` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`rule_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`rule_product` (
  `RULE_ID` BIGINT(20) NOT NULL,
  `PRODUCT_ID` BIGINT(20) NOT NULL,
  INDEX `FKapjjphnnmlgue4w44h8ansxjs` (`PRODUCT_ID` ASC),
  INDEX `FKdjggd8mhdjpo1upb7wy0pdbrm` (`RULE_ID` ASC),
  CONSTRAINT `FKapjjphnnmlgue4w44h8ansxjs`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `spsec`.`product` (`PRODUCT_ID`),
  CONSTRAINT `FKdjggd8mhdjpo1upb7wy0pdbrm`
    FOREIGN KEY (`RULE_ID`)
    REFERENCES `spsec`.`promotion_rule` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spsec`.`user_authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spsec`.`user_authority` (
  `USER_ID` BIGINT(20) NOT NULL,
  `AUTHORITY_ID` BIGINT(20) NOT NULL,
  INDEX `FKBC8EF3AF18CDC028` (`USER_ID` ASC),
  INDEX `FKBC8EF3AFE0C614C` (`AUTHORITY_ID` ASC),
  CONSTRAINT `FK5o90demi9pdvawuvokvkqhfg2`
    FOREIGN KEY (`AUTHORITY_ID`)
    REFERENCES `spsec`.`authority` (`ID`),
  CONSTRAINT `FKBC8EF3AF18CDC028`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `spsec`.`user` (`id`),
  CONSTRAINT `FKBC8EF3AFE0C614C`
    FOREIGN KEY (`AUTHORITY_ID`)
    REFERENCES `spsec`.`authority` (`ID`),
  CONSTRAINT `FKkqt0we0xoa20dcsogl5gqrhsl`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `spsec`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
