SET SQL_SAFE_UPDATES = 0;
delete from benefit_product;
delete from benefit;
delete from order_detail;
delete from purchase_order;
delete from product_category;
delete from product;
delete from type;
delete from brand;
delete from category;
delete from article;
