SET SQL_SAFE_UPDATES = 0;

delete from promo_categories;
delete from promo_product;
delete from promo_types;
delete from rule_product;
delete from promotion;
delete from promotion_rule;
delete from benefit_product;
delete from order_detail;
delete from purchase_order;
delete from benefit;
delete from product_category;
delete from product_flavor;
delete from flavor;
delete from product;
delete from type;
delete from brand;
delete from category;
delete from article_tags;
delete from article;
delete from tags;